### ISSUE TITLE
Update review site action to use the login-action to log into GitHub Container Registry.

### ISSUE THREAD

**Issue by trackleft** [az-digital/arizona-bootstrap#1284]
## Motivation
<img width="1247" alt="image" src="https://github.com/user-attachments/assets/a2ace1ec-d0e0-4701-b3ec-5f0b15646edd">

## Proposed Resolution
Currently we do this
```
      - name: Docker authentication
        run: |
          docker login "$AZ_DOCKER_REGISTRY" -u "$GITHUB_ACTOR" -p ${{ secrets.AZ_DOCKER_REGISTRY_TOKEN }}
```

Change how we log into the docker registry to 

https://github.com/docker/login-action#github-container-registry

```
- name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: $AZ_DOCKER_REGISTRY
          username: $GITHUB_ACTOR
          password:  ${{ secrets.AZ_DOCKER_REGISTRY_TOKEN }}
```
