### ISSUE TITLE
Dependabot not detecting updates for GitHub actions

### ISSUE THREAD

**Issue by joeparsons** [az-digital/arizona-bootstrap#1359]
## Problem/Motivation
We noticed that a dependabot PR was never created for #993.

## Proposed resolution
Description of the proposed solution, the rationale behind it, and workarounds for people who cannot use the patch.

##  Screenshots
If applicable, add screenshots to help explain your problem. (Need a tool to share screenshots or screencasts as URLs? Try [monosnap](https://monosnap.com)

**Comment by mmunro-ltrr** [comment]
There's already a section in `.github/dependabot.yml` intended to cover this:
```
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "az-digital/developers"
    labels:
      - "ci"
```
(but I don't understand why it doesn't work). Documentation is at
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
