### ISSUE TITLE
Add shellcheck step to PR process.

### ISSUE THREAD

**Issue by trackleft** [az-digital/arizona-bootstrap#465]
## Motivation
It would be good to find errors in our bash script files before updating the main branch.

### Is your feature request related to a problem? Please describe.
This is more of a prevention step to make it easier for non bash experts to contribute bash scripts to the project.

## Proposed Resolution
Use something similar to this.
```
name: Pull request checks
on: pull_request

jobs:
  lint-bash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Run ShellCheck
        uses: azohra/shell-linter@v0.6.0
        with:
          exclude-paths: Dockerfile, .github/CODEOWNERS, .github/ISSUE_TEMPLATE

```
